### ISSUE TITLE
Strange lines in legato-af / framework / c / src / thread.c 

### ISSUE THREAD

**Issue by JonoJensen** [legatoproject/legato-af#5]
legato-af / framework / c / src / thread.c 

The 2 lines (593,602):
if (pthread_attr_setschedpolicy(&(threadPtr->attr), SCHED_OTHER) == 0)
if (pthread_attr_setschedpolicy(&(threadPtr->attr), SCHED_IDLE) == 0)

Looks strange, shall it not be "!= 0" instead of "== 0"?

Regards /Jon

**Comment by jtchitty** [comment]
Definitely looks wrong to me too.

**Comment by jtchitty** [comment]
There's another bug in there too.  You can't use pthread_attr_setschedpolicy() to set SCHED_IDLE.

So, if you use le_thread_SetPriority() to set LE_THREAD_PRIORITY_IDLE, it will fail, but the reverse logic in the error code check will make you think it succeeded.  The result will be a thread that runs at NORMAL priority (SCHED_OTHER in POSIX terms).

If you use le_thread_SetPriority() to set LE_THREAD_PRIORITY_NORMAL, it will succeed, but will report a critical error in the log telling you that it failed.  The good news is that NORMAL is almost certainly your default priority, so you don't really need to do that ever anyway. :)  (That's probably why no one noticed it until now.)

The fix for the backward logic is obvious, but to fix the IDLE case, it's a bit trickier.  We need to have the thread itself use sched_setscheduler() to set the policy to SCHED_IDLE when it starts up instead.

**Comment by CoRfr** [comment]
Issue has been addressed in 16.04.0
